version: '3.9'

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    command:
      --pilot.token=${TOKEN}
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/etc/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=myresolver"
      - "traefik.http.routers.${APP_NAME}.service=api@internal"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=888"
      - "traefik.http.middlewares.${APP_NAME}-auth.basicauth.users=admin:${PASSWORD}"
      - "traefik.http.routers.${APP_NAME}.middlewares=${APP_NAME}-auth"

networks:
  default:
    external: 
      name: traefik