# log:
#   level: DEBUG

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: /etc/traefik/dynamic_conf.yml

certificatesResolvers:
  myresolver:
    acme:
      email: gossteerplus@gmail.com
      storage: acme.json
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web




